// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApxy2QfBXoFgePGcY4I6q1tyAMUhwNyaA',
    appId: '1:65631258059:web:6d105df35a901a866be24e',
    messagingSenderId: '65631258059',
    projectId: 'umakan-af531',
    authDomain: 'umakan-af531.firebaseapp.com',
    storageBucket: 'umakan-af531.appspot.com',
    measurementId: 'G-VFZ082XN81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABIXOu7ijwZeai5Ny6zg6I1VXCjeBcQrc',
    appId: '1:65631258059:android:fbde538ac9277ef66be24e',
    messagingSenderId: '65631258059',
    projectId: 'umakan-af531',
    storageBucket: 'umakan-af531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkspfnfrmbCs2LSlPWgCkGSR3kOSoajCc',
    appId: '1:65631258059:ios:1f83ebd874a49c5a6be24e',
    messagingSenderId: '65631258059',
    projectId: 'umakan-af531',
    storageBucket: 'umakan-af531.appspot.com',
    androidClientId: '65631258059-vr7an5lavavh34jina59c4a23d021vl5.apps.googleusercontent.com',
    iosClientId: '65631258059-vckgru0i92hb5p409kr03l1ptri3cn39.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypUmakan',
  );

}